### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by ljwtorch** [H-xiaoH/nonebot-plugin-apex-api-query#10]
ModuleNotFoundError: No module named 'nonebot_plugin_apex_api_query'

我更换了nonebot  nonebot2 都会提示这个问题，麻烦看一下应该怎么操作

nb: nonebot cli version 1.0.4

**Comment by H-xiaoH** [comment]
请附上完整错误日志。

**Comment by ljwtorch** [comment]
02-07 10:38:19 [ERROR] nonebot | Failed to import "nonebot_plugin_apex_api_query"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/home/torch/first-bot/.venv/lib/python3.8/site-packages/nonebot/plugin/load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/home/torch/first-bot/.venv/lib/python3.8/site-packages/nonebot/plugin/load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()
  File "/home/torch/first-bot/.venv/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
    return set(
  File "/home/torch/first-bot/.venv/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/home/torch/first-bot/.venv/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nonebot_plugin_apex_api_query'

**Comment by H-xiaoH** [comment]
似乎不是本插件的问题。由于您使用了虚拟环境，建议检查安装时是否在虚拟环境里执行指令。您可以在 `/home/torch/first-bot/.venv/lib/python3.8/site-packages/` 中查找是否存在 `nonebot_plugin_apex_api_query`。如不存在则可能存在上述问题。

**Comment by ljwtorch** [comment]
您说的路径中，我找到了nonebot_plugin_apex_api_query-22.11.10.dist-info这个文件夹，等会我自己再试试

**Comment by H-xiaoH** [comment]
需要仅名为 `nonebot_plugin_apex_api_query` 的文件夹。而且最新版本为 23.2.2 您提供是的 22.11.10 。
