### ISSUE TITLE
请问为什么一直出现[ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_apex_api_query) failed.

### ISSUE THREAD

**Issue by WasTed77** [H-xiaoH/nonebot-plugin-apex-api-query#19]
[INFO] nonebot | Matcher(type='message', module=nonebot_plugin_apex_api_query) running complete
**### **### 05-08 00:09:56 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_apex_api_query) failed.
Traceback (most recent call last):****
  File "<string>", line 17, in <module>
  File "C:\Users\14898.DESKTOP-G90AUDT\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\14898.DESKTOP-G90AUDT\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "C:\Users\14898.DESKTOP-G90AUDT\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "C:\Users\14898.DESKTOP-G90AUDT\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\14898.DESKTOP-G90AUDT\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\14898.DESKTOP-G90AUDT\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\14898.DESKTOP-G90AUDT\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\14898.DESKTOP-G90AUDT\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\14898.DESKTOP-G90AUDT\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\14898.DESKTOP-G90AUDT\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\14898.DESKTOP-G90AUDT\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\14898.DESKTOP-G90AUDT\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\14898.DESKTOP-G90AUDT\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\14898.DESKTOP-G90AUDT\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
    await handler(
  File "C:\Users\14898.DESKTOP-G90AUDT\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\14898.DESKTOP-G90AUDT\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_apex_api_query\__init__.py", line 142, in crafting_func
    msg = await t2i(service, response)
  File "C:\Users\14898.DESKTOP-G90AUDT\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_apex_api_query\__init__.py", line 273, in t2i
    pic = Txt2Img().draw(title, text)
  File "C:\Users\14898.DESKTOP-G90AUDT\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_txt2img\txt2img.py", line 81, in draw
    title_font = ImageFont.truetype(self.font_family, self.title_font_size)
  File "C:\Users\14898.DESKTOP-G90AUDT\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\ImageFont.py", line 996, in truetype
    return freetype(font)
  File "C:\Users\14898.DESKTOP-G90AUDT\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\ImageFont.py", line 993, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "C:\Users\14898.DESKTOP-G90AUDT\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\ImageFont.py", line 248, in __init__
    self.font = core.getfont(
OSError: cannot open resource
抱歉我是小白  不知道以何种方便的方式进行提问

**Comment by H-xiaoH** [comment]
https://github.com/H-xiaoH/nonebot-plugin-apex-api-query/issues/7

**Comment by WasTed77** [comment]
> #7

谢谢！！！

**Comment by WasTed77** [comment]
> #7

plugins = ["nonebot_plugin_gocqhttp", "nonebot_plugin_manager", "nonebot_plugin_apex_api_query", "nonebot_plugin_txt2img"]
我下载了这两个插件了但还是依旧如上报错

**Comment by H-xiaoH** [comment]
> > #7
> 
> plugins = ["nonebot_plugin_gocqhttp", "nonebot_plugin_manager", "nonebot_plugin_apex_api_query", "nonebot_plugin_txt2img"] 我下载了这两个插件了但还是依旧如上报错

你不需要手动安装此插件。因为本插件的依赖中已经包含。
你需要将 https://github.com/mobyw/nonebot-plugin-txt2img/tree/main/data/TXT2IM 中的内容放置在您的 nb 目录中。
