### ISSUE TITLE
萌新求问 q群输入指令后报错

### ISSUE THREAD

**Issue by Parirose** [H-xiaoH/nonebot-plugin-apex-api-query#21]
[ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_apex_api_query) failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\bot.py", line 17, in <module>
    nonebot.run()
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\__init__.py", line 309, in
 run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line
198, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\uvicorn\server.py", line 61, in ru
n
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_unt
il_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_
forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_for
ever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_o
nce
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\message.py", line 141, in
_check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\message.py", line 187, in
_run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\internal\matcher\matcher.p
y", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\internal\matcher\matcher.p
y", line 728, in simple_run
    await handler(
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\dependencies\__init__.py",
 line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot_plugin_apex_api_query\__in
it__.py", line 142, in crafting_func
    msg = await t2i(service, response)
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot_plugin_apex_api_query\__in
it__.py", line 273, in t2i
    pic = Txt2Img().draw(title, text)
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot_plugin_txt2img\txt2img.py"
, line 81, in draw
    title_font = ImageFont.truetype(self.font_family, self.title_font_size)
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\PIL\ImageFont.py", line 996, in tr
uetype
    return freetype(font)
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\PIL\ImageFont.py", line 993, in fr
eetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\PIL\ImageFont.py", line 248, in __
init__
    self.font = core.getfont(
OSError: cannot open resource

以上是报错的日志 似乎是没找到字体？ 这是否和其他插件的字体会冲突？ 想问问这个应该怎么解决 感谢大佬

**Comment by H-xiaoH** [comment]
#7 #19

**Comment by Parirose** [comment]
感谢大佬!
