### ISSUE TITLE
手动下载/data后出现另一个报错

### ISSUE THREAD

**Issue by Arasi2333** [H-xiaoH/nonebot-plugin-apex-api-query#23]
Running Matcher(type='message', module=nonebot_plugin_apex_api_query) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/root/Arasi/.venv/lib/python3.11/site-packages/nonebot/__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "/root/Arasi/.venv/lib/python3.11/site-packages/nonebot/drivers/fastapi.py", line 199, in run
    uvicorn.run(
  File "/root/Arasi/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/root/Arasi/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/root/Arasi/.venv/lib/python3.11/site-packages/nonebot/message.py", line 467, in check_and_run_matcher
    await _run_matcher(
> File "/root/Arasi/.venv/lib/python3.11/site-packages/nonebot/message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/Arasi/.venv/lib/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 759, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/Arasi/.venv/lib/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 734, in simple_run
    await handler(
  File "/root/Arasi/.venv/lib/python3.11/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/Arasi/.venv/lib/python3.11/site-packages/nonebot_plugin_apex_api_query/__init__.py", line 123, in map_func
    msg = await t2i(service, response)
  File "/root/Arasi/.venv/lib/python3.11/site-packages/nonebot_plugin_apex_api_query/__init__.py", line 280, in t2i
    pic = Txt2Img().draw(title, text)
  File "/root/Arasi/.venv/lib/python3.11/site-packages/nonebot_plugin_txt2img/txt2img.py", line 81, in draw
    title_font = ImageFont.truetype(self.font_family, self.title_font_size)
  File "/root/Arasi/.venv/lib/python3.11/site-packages/PIL/ImageFont.py", line 996, in truetype
    return freetype(font)
  File "/root/Arasi/.venv/lib/python3.11/site-packages/PIL/ImageFont.py", line 993, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/root/Arasi/.venv/lib/python3.11/site-packages/PIL/ImageFont.py", line 248, in __init__
    self.font = core.getfont(
OSError: unknown file format

**Comment by H-xiaoH** [comment]
我看了一下 [nonebot-plugin-txt2img](https://github.com/mobyw/nonebot-plugin-txt2img) 没有更新。
可以检查一下您的目录中的文件完整性是否正确？
重新下载一次文件 或者 提供各文件路径 检查。

**Comment by Arasi2333** [comment]
> 我看了一下 [nonebot-plugin-txt2img](https://github.com/mobyw/nonebot-plugin-txt2img) 没有更新。 可以检查一下您的目录中的文件完整性是否正确？ 重新下载一次文件 或者 提供各文件路径 检查。

我应该检查哪些目录中的文件完整性呢，我用wget重新下载过/data中的每一个文件，也试过更新nonebot-plugin-txt2img，还有删除nonebot-plugin-txt2img和nonebot-plugin-apex-api-query重新安装，依然会出现这个报错

**Comment by H-xiaoH** [comment]
> 我应该检查哪些目录中的文件完整性呢，我用wget重新下载过/data中的每一个文件，也试过更新nonebot-plugin-txt2img，还有删除nonebot-plugin-txt2img和nonebot-plugin-apex-api-query重新安装，依然会出现这个报错

emmmm 我刚刚去 Google 了一下，似乎是 Linux 不能直接使用 Windows 的字体文件。(?
尝试在 Linux 系统的字体库的文件夹内复制一份中文字体文件并重命名到 /data 文件夹覆盖里面的字体文件试试？

**Comment by Arasi2333** [comment]
> > 我应该检查哪些目录中的文件完整性呢，我用wget重新下载过/data中的每一个文件，也试过更新nonebot-plugin-txt2img，还有删除nonebot-plugin-txt2img和nonebot-plugin-apex-api-query重新安装，依然会出现这个报错
> 
> emmmm 我刚刚去 Google 了一下，似乎是 Linux 不能直接使用 Windows 的字体文件。(? 尝试在 Linux 系统的字体库的文件夹内复制一份中文字体文件并重命名到 /data 文件夹覆盖里面的字体文件试试？

我找到错误的来源了，使用wget下载的/data/TXT2IMG/font/sarasa-mono-sc-regular.ttf会导致报错，我用另一台windows电脑下载了/data文件夹之后用Xshell复制进去就正常了
