### ISSUE TITLE
无法返回查询结果

### ISSUE THREAD

**Issue by thankU-ubi** [H-xiaoH/nonebot-plugin-apex-api-query#7]
能正常返回文字 比如 
正在查询: 地图轮换 
正在查询: 顶尖猎杀者
但是结果在后台是报错
使用的是新版nonebot rc3虚拟环境
01-19 07:50:40 [INFO] nonebot_plugin_gocqhttp | [2821521344] 发送群 测试群(606749081) 的消息: [{"type":  ... (1575284129)
01-19 07:50:41 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_apex_api_query) running complete
01-19 07:50:41 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_apex_api_query) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "C:\BOT\BOT\test\.venv\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\BOT\BOT\test\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\BOT\BOT\test\.venv\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\BOT\BOT\test\.venv\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\BOT\BOT\test\.venv\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\BOT\BOT\test\.venv\lib\site-packages\nonebot\message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\BOT\BOT\test\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\BOT\BOT\test\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 702, in simple_run
    await handler(
  File "C:\BOT\BOT\test\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\BOT\BOT\test\.venv\lib\site-packages\nonebot_plugin_apex_api_query\__init__.py", line 79, in _
    msg = t2i(service, response)
  File "C:\BOT\BOT\test\.venv\lib\site-packages\nonebot_plugin_apex_api_query\__init__.py", line 222, in t2i
    pic = Txt2Img().draw(title, text)
  File "C:\BOT\BOT\test\.venv\lib\site-packages\nonebot_plugin_txt2img\txt2img.py", line 81, in draw
    title_font = ImageFont.truetype(self.font_family, self.title_font_size)
  File "C:\BOT\BOT\test\.venv\lib\site-packages\PIL\ImageFont.py", line 1008, in truetype
    return freetype(font)
  File "C:\BOT\BOT\test\.venv\lib\site-packages\PIL\ImageFont.py", line 1005, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "C:\BOT\BOT\test\.venv\lib\site-packages\PIL\ImageFont.py", line 255, in __init__
    self.font = core.getfont(
OSError: cannot open resource

**Comment by H-xiaoH** [comment]
本插件的依赖 [nonebot-plugin-txt2img](https://github.com/mobyw/nonebot-plugin-txt2img) 所需的文件没有下载完成，您可以手动下载并安装 /data 文件夹以修复此问题。
